; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = test
; default_envs = deepsleep

src_dir = examples/${platformio.default_envs}
boards_dir = platformio/boards

[env]
platform = espressif32@6.12.0
board = lilygo-t7-s3
framework = arduino
upload_protocol = esptool
upload_speed = 921600
monitor_speed = 115200
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1

[env:test]

[env:deepsleep]
